name: your-workflow-name
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python train.py
          
          # Post reports as comments in GitHub PRs
          echo "## Trianing Report" > report.md
          cat report.txt >> report.md
          
          cml-publish confusion_mat.png --md >> report.md
          
          cml-send-comment report.md
